# Problema 1

Las matrices $A$ y $B$ representan las ventas en dos años, en millones de dólares, de los tres productos de una empresa en las cuatro regiones en que está disponible. Es decir, $a_{ij}$ y $b_{ij}$ representan el monto de las ventas del producto $i$ en la región $j$ el primer y segundo año, respectivamente:

<br>

\begin{split}
A = \begin{pmatrix}
 2,6 &  4,8 &  1,8 & 0,9 \\
 3,2 &  4,4 &  2,5 & 2,8 \\
 2,4 &  3,6 &  3,8 & 2,5 \\
\end{pmatrix} \text{ } B= \begin{pmatrix}
 3,6 &  2,5 &  3,0 & 2,5 \\
 4,5 &  5,0 &  3,5 & 3,8 \\
 2,9 &  3,0 &  4,6 & 4,0 \\
\end{pmatrix}
\end{split}

<br>

1. Indique el orden de cada matriz.
2. Calcule la matriz $S = A + B$.
3. Calcule la matriz $D = B - A$.
4. Indique el valor e interprete los elementos $s_{24}$ y $d_{24}$.
5. Para el tercer año de funcionamiento, los tres productos ahora están disponibles en seis regiones. Durante este año, las ventas de esta empresa estarán registradas en una matriz $E$. ¿Es posible determinar la matriz $T = A + B + E$? Justifique su respuesta.

In [1]:
import numpy as np

# Definimos las matrices A y B
A = np.array([
    [2.6, 4.8, 1.8, 0.9],
    [3.2, 4.4, 2.5, 2.8],
    [2.4, 3.6, 3.8, 2.5]
])

B = np.array([
    [3.6, 2.5, 3.0, 2.5],
    [4.5, 5.0, 3.5, 3.8],
    [2.9, 3.0, 4.6, 4.0]
])

# 2. Calcular S = A + B
S = A + B
print("--- Matriz S (Ventas Totales) ---")
print(S)

# 3. Calcular D = B - A
D = B - A
print("\n--- Matriz D (Diferencia de Ventas) ---")
print(D)

# 4. Interpretar s_24 y d_24
# En Python, los índices empiezan en 0, así que [1, 3] es la fila 2, columna 4.
s_24 = S[1, 3]
d_24 = D[1, 3]

print(f"\nValor de s_24: {s_24:.1f}")
print(f"Valor de d_24: {d_24:.1f}")

--- Matriz S (Ventas Totales) ---
[[6.2 7.3 4.8 3.4]
 [7.7 9.4 6.  6.6]
 [5.3 6.6 8.4 6.5]]

--- Matriz D (Diferencia de Ventas) ---
[[ 1.  -2.3  1.2  1.6]
 [ 1.3  0.6  1.   1. ]
 [ 0.5 -0.6  0.8  1.5]]

Valor de s_24: 6.6
Valor de d_24: 1.0


# Problema 2

Una fábrica con sucursales en Japón y China, produce tres tipos de componentes $j$, para cinco modelos de computador $i$. Los costos de producción mensual, en miles de dólares, de ambas sucursales se representan en las matrices $J$ y $C$, respectivamente:

<br>

\begin{split}
J = \begin{pmatrix}
 100 &  200 &  150  \\
 120 &  210 &  170  \\
 112 &  200 &  131  \\
 124 &  310 &  170  \\
 136 &  156 &  140  \\
\end{pmatrix} \text{ } C = \begin{pmatrix}
 110 &  190 &  160  \\
 130 &  220 &  180  \\
 146 &  190 &  141  \\
 143 &  312 &  163  \\
 137 &  116 &  156  \\
\end{pmatrix}
\end{split}

<br>

1. ¿Cuál es el orden de las matrices?
2. Inteprete el elemento $j_{21}$ y $c_{12}$ en el contexto del problema.
3. Utilizando *Python*, calcule el costo total de producción para cada modelo, considerando ambas sucursales.
4. Un trabajador indica que, en la sucursal japonesa, el costo de producción del producto $3$, modelo $4$ de computador, es más alto que en la sucursal china. ¿Tiene razón? Justifique apropiadamente.

In [2]:
import numpy as np

# Definimos las matrices J y C
J = np.array([
    [100, 200, 150],
    [120, 210, 170],
    [112, 200, 131],
    [124, 310, 170],
    [136, 156, 140]
])

C = np.array([
    [110, 190, 160],
    [130, 220, 180],
    [146, 190, 141],
    [143, 312, 163],
    [137, 116, 156]
])

# 3. Calcular la matriz de Costos Totales (Suma de matrices)
Total_Costos = J + C

print("--- Matriz de Costos Totales (J + C) ---")
print(Total_Costos)

--- Matriz de Costos Totales (J + C) ---
[[210 390 310]
 [250 430 350]
 [258 390 272]
 [267 622 333]
 [273 272 296]]


# Problema 3

La empresa Beta tiene cinco plantas en Chile, y en cada una de ellas fabrica siete productos. El número de unidades del producto $i$ fabricadas en la planta $j$ en una semana está representado en la matriz $C$ en el elemento $c_{ij}$.

<br>

\begin{split}
C = \begin{pmatrix}
 120 &  200 &  155 &  125  &  230 \\
 155 &  130 &  110 &  160  &  180 \\
 140 &  205 &  150 &  125  &  155 \\
 130 &  120 &  230 &  225  &  125 \\
 135 &  70  &  190 &  175  &  95  \\
 110 &  265 &  180 &  230  &  180 \\
 185 &  85  &  120 &  135  &  150 \\
\end{pmatrix}
\end{split}

<br>

La empresa se expande, creando cinco plantas en Ecuador que producen los mismos siete productos. La producción semanal de esta filial estará representada por una matriz $E$.

1. Si se sabe que los volúmenes de producción semanal de la filial en Ecuador son un $20\%$ menor que en Chile, calcule la matriz $E$ utilizando *Python*.
2. Si representamos la producción semanal total de la empresa Beta, considerando ambas filiales, por la matriz $T$, escriba la expresión que calcula cada elemento de la matriz $T$ usando notación matricial.
3. Calcule la matriz $T$ utilizando *Python*.
4. Interprete los elementos $c_{34}$ y $t_{72}$ en el contexto del problema.

In [8]:
import numpy as np

# Matriz C (Chile)
C = np.array([
    [120, 200, 155, 125, 230],
    [155, 130, 110, 160, 180],
    [140, 205, 150, 125, 155],
    [130, 120, 230, 225, 125],
    [135,  70, 190, 175,  95],
    [110, 265, 180, 230, 180],
    [185,  85, 120, 135, 150]
])

# 1. Calcular la matriz E (Producción Ecuador)
E = 0.8 * C
print("--- 1. Matriz E (Producción Ecuador) ---")
# Usamos .astype(int) para mostrar números enteros, ya que no se pueden fabricar unidades decimales.
print(E.astype(int))

# 2. Expresión matricial para T
print("\n--- 2. Expresión Matricial ---")
print("La expresión que calcula T es: T = C + E")

# 3. Calcular la matriz T (Producción Total)
T = C + E
print("\n--- 3. Matriz T (Producción Total) ---")
print(T)

# 4. Interpretación de elementos
# Recordamos que Python usa índices desde 0.
# c_34 es fila 3, columna 4 -> índice [2, 3]
# t_72 es fila 7, columna 2 -> índice [6, 1]

c_34 = C[2, 3]
t_72 = T[6, 1]

print("\n--- 4. Interpretación de Elementos ---")
print(f"El elemento c_34 ({c_34}) representa la producción de 125 unidades del producto 3 en la planta 4 de la filial en Chile.")
print(f"El elemento t_72 ({t_72}) representa la producción total de 153 unidades del producto 7 en la planta 2, sumando las filiales de Chile y Ecuador.")

--- 1. Matriz E (Producción Ecuador) ---
[[ 96 160 124 100 184]
 [124 104  88 128 144]
 [112 164 120 100 124]
 [104  96 184 180 100]
 [108  56 152 140  76]
 [ 88 212 144 184 144]
 [148  68  96 108 120]]

--- 2. Expresión Matricial ---
La expresión que calcula T es: T = C + E

--- 3. Matriz T (Producción Total) ---
[[216. 360. 279. 225. 414.]
 [279. 234. 198. 288. 324.]
 [252. 369. 270. 225. 279.]
 [234. 216. 414. 405. 225.]
 [243. 126. 342. 315. 171.]
 [198. 477. 324. 414. 324.]
 [333. 153. 216. 243. 270.]]

--- 4. Interpretación de Elementos ---
El elemento c_34 (125) representa la producción de 125 unidades del producto 3 en la planta 4 de la filial en Chile.
El elemento t_72 (153.0) representa la producción total de 153 unidades del producto 7 en la planta 2, sumando las filiales de Chile y Ecuador.


# Problema 4

Una empresa que fabrica zapatos tiene dos plantas, una en Valparaíso y la otra en Temuco. La empresa produce zapatos de color negro, blanco y café, tanto para niños, damas como caballeros. La capacidad actual de producción mensual (en miles de pares) para Valparaíso y Temuco, están dadas por las matrices $V$ y $T$, respectivamente. Para ambas matrices, según el orden en que se mencionan, las filas corresponden al color del calzado y las columnas al tipo de persona que utilizará el calzado.

<br>

\begin{split}
V = \begin{pmatrix}
 30 &  34 &  20  \\
 45 &  20 &  16  \\
 14 &  26 &  25  \\
\end{pmatrix} \text{ } T = \begin{pmatrix}
 35 &  30 &  26  \\
 52 &  25 &  18  \\
 23 &  24 &  32  \\
\end{pmatrix}
\end{split}

<br>

1. Determine la producción mensual total de ambas plantas, representándola en una matriz $A$. Utilice *Python* para resolver.
2. Interprete el elemento $a_{21}$ en el contexto del problema.
3. Si para el próximo año se estima que la producción en Valparaíso aumenta en un $30\%$, mientras que la de Temuco se reduce en un $10\%$, represente la nueva producción total en la matriz $B$.
4. Interprete el elemento $b_{13}$ en el contexto del problema.

In [ ]:
import numpy as np

# Matriz V (Valparaíso) y T (Temuco)
V = np.array([
    [30, 34, 20],
    [45, 20, 16],
    [14, 26, 25]
])

T = np.array([
    [35, 30, 26],
    [52, 25, 18],
    [23, 24, 32]
])

# 1. Producción mensual total A
A = V + T
print("--- 1. Matriz A (Producción Total Actual) ---")
print(A)

# 2. Interprete a_21
# Fila 2, Columna 1 -> índice [1, 0]
a_21 = A[1, 0]
print("\n--- 2. Interpretación a_21 ---")
print(f"a_21 ({a_21}) representa la producción total mensual de 97 mil pares de zapatos de color Blanco para Niños.")

# 3. Nueva producción B (Valparaíso +30%, Temuco -10%)
V_nueva = V * 1.30
T_nueva = T * 0.90
B = V_nueva + T_nueva
print("\n--- 3. Matriz B (Nueva Producción Total) ---")
print(B)

# 4. Interprete b_13
# Fila 1, Columna 3 -> índice [0, 2]
b_13 = B[0, 2]
print("\n--- 4. Interpretación b_13 ---")
print(f"b_13 ({b_13:.1f}) representa la producción total mensual esperada de 49.4 mil pares de zapatos de color Negro para Caballeros.")

# Problema 5

Genere una matriz $M$ de orden $8 \times 9$ donde cada término de la matriz está definido por:

$$m_{ij} = 8i + 12j$$

y calcule su transpuesta.

In [2]:
import numpy as np

# Usamos np.fromfunction. (8, 9) es el orden de la matriz.
# i tomará valores de 0 a 7.
# j tomará valores de 0 a 8.
M = np.fromfunction(lambda i, j: 8*i + 12*j, (8, 9), dtype=int)

print("--- Matriz M (m_ij = 8i + 12j) ---")
print(M)

# Calcular la transpuesta usando .T
M_transpuesta = M.T

print("\n--- Matriz Transpuesta (M.T) ---")
print(M_transpuesta)

--- Matriz M (m_ij = 8i + 12j) ---
[[  0  12  24  36  48  60  72  84  96]
 [  8  20  32  44  56  68  80  92 104]
 [ 16  28  40  52  64  76  88 100 112]
 [ 24  36  48  60  72  84  96 108 120]
 [ 32  44  56  68  80  92 104 116 128]
 [ 40  52  64  76  88 100 112 124 136]
 [ 48  60  72  84  96 108 120 132 144]
 [ 56  68  80  92 104 116 128 140 152]]

--- Matriz Transpuesta (M.T) ---
[[  0   8  16  24  32  40  48  56]
 [ 12  20  28  36  44  52  60  68]
 [ 24  32  40  48  56  64  72  80]
 [ 36  44  52  60  68  76  84  92]
 [ 48  56  64  72  80  88  96 104]
 [ 60  68  76  84  92 100 108 116]
 [ 72  80  88  96 104 112 120 128]
 [ 84  92 100 108 116 124 132 140]
 [ 96 104 112 120 128 136 144 152]]


# Problema 6

Genere dos matrices:

*   Una matriz $A$ de orden $5 \times 7$, con $a_{ij} = i \cdot j.$
*   Una matriz $B$ de orden $7 \times 5$, con $b_{ij} = 15i - 2j.$

y calcule $C = A^{T} + \dfrac{1}{2}B$.



In [3]:
import numpy as np

# Usamos np.fromfunction. (8, 9) es el orden de la matriz.
# i tomará valores de 0 a 7.
# j tomará valores de 0 a 8.
M = np.fromfunction(lambda i, j: 8*i + 12*j, (8, 9), dtype=int)

print("--- Matriz M (m_ij = 8i + 12j) ---")
print(M)

# Calcular la transpuesta usando .T
M_transpuesta = M.T

print("\n--- Matriz Transpuesta (M.T) ---")
print(M_transpuesta)

--- Matriz M (m_ij = 8i + 12j) ---
[[  0  12  24  36  48  60  72  84  96]
 [  8  20  32  44  56  68  80  92 104]
 [ 16  28  40  52  64  76  88 100 112]
 [ 24  36  48  60  72  84  96 108 120]
 [ 32  44  56  68  80  92 104 116 128]
 [ 40  52  64  76  88 100 112 124 136]
 [ 48  60  72  84  96 108 120 132 144]
 [ 56  68  80  92 104 116 128 140 152]]

--- Matriz Transpuesta (M.T) ---
[[  0   8  16  24  32  40  48  56]
 [ 12  20  28  36  44  52  60  68]
 [ 24  32  40  48  56  64  72  80]
 [ 36  44  52  60  68  76  84  92]
 [ 48  56  64  72  80  88  96 104]
 [ 60  68  76  84  92 100 108 116]
 [ 72  80  88  96 104 112 120 128]
 [ 84  92 100 108 116 124 132 140]
 [ 96 104 112 120 128 136 144 152]]


# Problema 7

Una red de sensores recoge datos de temperatura ($°C$), humedad (porcentaje) y presión (hPa) en cinco días distintos (de lunes a viernes). Los datos medidos se muestran en la matriz $D$:

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
 & Lu  \ \ &Ma \ \ &Mi \ \ & Ju \ \ &Vi
\end{matrix} \\
&D = \begin{pmatrix}
20    &  28    &  22    &  26     &  24   \\
52    &  57    &  56    &  54     &  58   \\
1.066 &  1.068 &  1.066 &  1.064  &  1.068 \\
\end{pmatrix} & \ \begin{matrix}
Cº\\
\% \\
hPa
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

Se sabe que por un error de calibración de los sensores, las medidas registradas deberían ser un $5\%$ menores que las registradas.

1. Calcule en una matriz $S$ los valores correctos de temperatura, humedad y presión. Utilice *Python* para calcular.
2. Obtenga la matriz $S^{T}$.
3. Interprete los elementos $s_{24}$ y $s_{31}^{T}$.


In [2]:
import numpy as np

# Matriz D (Datos originales)
D = np.array([
    [20.0,   28.0,   22.0,   26.0,   24.0],
    [52.0,   57.0,   56.0,   54.0,   58.0],
    [1066.0, 1068.0, 1066.0, 1064.0, 1068.0]
])

# 1. Calcule S (Valores 5% menores)
S = D * 0.95
print("--- 1. Matriz S (Datos Corregidos) ---")
print(np.round(S, 2)) # Redondeamos a 2 decimales

# 2. Obtenga S.T
S_T = S.T
print("\n--- 2. Matriz S Transpuesta (S.T) ---")
print(np.round(S_T, 2))

# 3. Interpretación
# s_24 -> Fila 2, Columna 4 de S
s_24 = S[1, 3]
# s_T_31 -> Fila 3, Columna 1 de S_T (que es Fila 1, Columna 3 de S)
s_T_31 = S_T[2, 0]

print("\n--- 3. Interpretación de Elementos ---")
print(f"s_24 ({s_24:.2f}): Es el valor de Humedad (fila 2) el día Jueves (columna 4), corregido a 51.30%.")
print(f"s_31^T ({s_T_31:.2f}): Es el valor de Temperatura (columna 1 de S_T) el día Miércoles (fila 3 de S_T), corregido a 20.90 °C.")



--- 1. Matriz S (Datos Corregidos) ---
[[  19.     26.6    20.9    24.7    22.8 ]
 [  49.4    54.15   53.2    51.3    55.1 ]
 [1012.7  1014.6  1012.7  1010.8  1014.6 ]]

--- 2. Matriz S Transpuesta (S.T) ---
[[  19.     49.4  1012.7 ]
 [  26.6    54.15 1014.6 ]
 [  20.9    53.2  1012.7 ]
 [  24.7    51.3  1010.8 ]
 [  22.8    55.1  1014.6 ]]

--- 3. Interpretación de Elementos ---
s_24 (51.30): Es el valor de Humedad (fila 2) el día Jueves (columna 4), corregido a 51.30%.
s_31^T (20.90): Es el valor de Temperatura (columna 1 de S_T) el día Miércoles (fila 3 de S_T), corregido a 20.90 °C.


# Problema 8

Una empresa tecnológica vende software y hardware en tres productos: $P_{1}$, $P_{2}$ y $P_{3}$, en cuatro zonas de la capital: norte, sur, este y oeste. Las ventas del mes, en millones de pesos, están registradas en las matrices $S$ y $H$, para software y hardware respectivamente.

<br>

\begin{split}
S = \begin{pmatrix}
 260 &  480 &  180  &  90  \\
 320 &  440 &  250  &  280 \\
 240 &  360 &  380  &  250  \\
\end{pmatrix} \text{ } H = \begin{pmatrix}
 360 &  250 &  300  &  250  \\
 450 &  500 &  350  &  380 \\
 290 &  300 &  460  &  400  \\
\end{pmatrix}
\end{split}

<br>

1. Calcule en la matriz $T$, del total de ventas de la empresa tecnológica.
2. Un trabajador indica que este mes, la sucursal de la zona sur recaudó más por la venta hardware que software, ¿es correcta su afirmación?
3. Debido al black friday se espera que el siguiente mes, las ventas de software aumenten un $7\%$ y las de hardware aumenten un $3\%$ respecto al mes actual. Encuentra en total de ventas esperadas para el siguiente mes y almacénalo en la matriz $M$. Utiliza *Python* para realizar los cálculos.
4. Interpreta los elementos $t_{24}$ y $m_{31}$ en el contexto del problema.
5. Calcula la matriz $M^{T}$ e interpreta el elemento $m_{41}^{T}$ en el contexto del problema.


In [1]:
import numpy as np

# Matriz S (Software) y H (Hardware)
S = np.array([
    [260, 480, 180,  90],
    [320, 440, 250, 280],
    [240, 360, 380, 250]
])

H = np.array([
    [360, 250, 300, 250],
    [450, 500, 350, 380],
    [290, 300, 460, 400]
])

# 1. Calcule T (Ventas Totales)
T = S + H
print("--- 1. Matriz T (Ventas Totales) ---")
print(T)

# 2. Afirmación del trabajador (Zona Sur = Columna índice 1)
# Usamos np.sum(matriz[:, indice_columna]) para sumar la columna
ventas_software_sur = np.sum(S[:, 1])
ventas_hardware_sur = np.sum(H[:, 1])

print("\n--- 2. Afirmación del Trabajador (Zona Sur) ---")
print(f"Ventas Software (Sur): {ventas_software_sur} millones")
print(f"Ventas Hardware (Sur): {ventas_hardware_sur} millones")
if ventas_hardware_sur > ventas_software_sur:
    print("La afirmación es CORRECTA.")
else:
    print("La afirmación es INCORRECTA. La zona sur recaudó más por Software (1280) que por Hardware (1050).")

# 3. Calcule M (Ventas mes siguiente: S +7%, H +3%)
M = (S * 1.07) + (H * 1.03)
print("\n--- 3. Matriz M (Ventas Siguiente Mes) ---")
print(np.round(M, 2))

# 4. Interprete t_24 y m_31
# t_24 -> Fila 2, Columna 4 de T
t_24 = T[1, 3]
# m_31 -> Fila 3, Columna 1 de M
m_31 = M[2, 0]
print("\n--- 4. Interpretación t_24 y m_31 ---")
print(f"t_24 ({t_24}): Ventas totales (en millones) del Producto 2 en la zona Oeste.")
print(f"m_31 ({m_31:.2f}): Ventas esperadas (en millones) del Producto 3 en la zona Norte para el próximo mes.")

# 5. Calcule M.T e interprete m_41^T
M_T = M.T
print("\n--- 5. Matriz M Transpuesta ---")
print(np.round(M_T, 2))
# m_41^T -> Fila 4, Columna 1 de M_T
m_T_41 = M_T[3, 0]
print(f"\nm_41^T ({m_T_41:.1f}): Ventas esperadas (en millones) de la zona Oeste (fila 4 de M_T) para el Producto 1 (columna 1 de M_T).")


--- 1. Matriz T (Ventas Totales) ---
[[620 730 480 340]
 [770 940 600 660]
 [530 660 840 650]]

--- 2. Afirmación del Trabajador (Zona Sur) ---
Ventas Software (Sur): 1280 millones
Ventas Hardware (Sur): 1050 millones
La afirmación es INCORRECTA. La zona sur recaudó más por Software (1280) que por Hardware (1050).

--- 3. Matriz M (Ventas Siguiente Mes) ---
[[649.  771.1 501.6 353.8]
 [805.9 985.8 628.  691. ]
 [555.5 694.2 880.4 679.5]]

--- 4. Interpretación t_24 y m_31 ---
t_24 (660): Ventas totales (en millones) del Producto 2 en la zona Oeste.
m_31 (555.50): Ventas esperadas (en millones) del Producto 3 en la zona Norte para el próximo mes.

--- 5. Matriz M Transpuesta ---
[[649.  805.9 555.5]
 [771.1 985.8 694.2]
 [501.6 628.  880.4]
 [353.8 691.  679.5]]

m_41^T (353.8): Ventas esperadas (en millones) de la zona Oeste (fila 4 de M_T) para el Producto 1 (columna 1 de M_T).
