# Problema 1

La fábrica de bicicletas Expend produce dos modelos de bicicletas, $M$ y $N$. La matriz $A$ nos indica las cantidades de acero y aluminio que requiere cada bicicleta, expresadas en kg según el modelo a producir, mientras que la matriz $B$ nos entrega un reporte de la cantidad de bicicletas producidas de ambos modelos para los dos primeros meses del año pasado.

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
 & \ \ \ \  M & N
\end{matrix}  \\
&A= \begin{pmatrix}
1 & 2 \\
3 & 2 \\
\end{pmatrix} & \ \begin{matrix}
Acero\\
Aluminio
\end{matrix}\\
\end{matrix}
\ \ \ \ \ \ \ \ \ \ \ \ \ \
\begin{matrix}
& \begin{matrix}
& \ \ \ \ \ \ \ ene & feb &
\end{matrix} & \\
&B= \begin{pmatrix}
290 &  312 \\
 345 &  413 \\
\end{pmatrix} & \begin{matrix}
M\\
N
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

1. Indique el orden de cada matriz. ¿Es posible determinar la multiplicación entre ambas matrices? Justifique.
2. Determine utilizando *Python* la matriz $C = A \cdot B$
3. Indique e interprete el valor de los elementos $c_{21}$ y $c_{11}$.

In [ ]:
import numpy as np

# Definimos las matrices A (Materiales x Modelo) y B (Modelo x Mes)
A = np.array([
    [1, 2], # Fila 1: Acero
    [3, 2]  # Fila 2: Aluminio
])

B = np.array([
    [290, 312], # Col 1: Ene, Col 2: Feb
    [345, 413]  # Fila 1: Modelo M, Fila 2: Modelo N
])

# 2. Calcular C = A * B (Multiplicación de matrices)
C = np.dot(A, B)

print("--- 2. Matriz C (Materiales x Mes) ---")
print(C)

# 3. Interpretación de elementos
# c_21 -> Fila 2, Columna 1 (Índice [1, 0])
c_21 = C[1, 0]
# c_11 -> Fila 1, Columna 1 (Índice [0, 0])
c_11 = C[0, 0]

print("\n--- 3. Interpretación de Elementos ---")
print(f"c_21 ({c_21}): Es la cantidad total de Aluminio (fila 2) necesaria para la producción del mes de Enero (columna 1).")
print(f"c_11 ({c_11}): Es la cantidad total de Acero (fila 1) necesaria para la producción del mes de Enero (columna 1).")

# Problema 2

Una pequeña cadena tiene restaurantes de comida rápida en Santiago, Concepción y Antofagasta, en los que vende hamburguesas, completos y mateadas. En un fin de semana, las cantidades de cada comida según cada sucursal se distribuyeron de acuerdo con la siguiente matriz $V$, donde las filas corresponden a los productos y las columnas a las sucursales, mientras que los precios, en pesos, de cada producto están expresados en la matriz $P$.

<br>

\begin{split}
V &= \begin{pmatrix}
 1300 &  900  &  800  \\
 2100 &  1700 &  1500 \\
 1500 &  1200 &  900  \\
\end{pmatrix}\\
\\
P &= \begin{pmatrix}
 4200 &  1500 & 3200 \\
\end{pmatrix}
\end{split}

<br>

Si $I = P \cdot V$

1. Indique el orden de cada matriz.
2. Determine utilizando *Python* la matriz $I$.
3. Indique e interprete el valor de los elementos $v_{32}$, $p_{12}$ e $i_{13}$.

In [1]:
import numpy as np

# Filas V: [Hamb, Comp, Mat]
# Cols V: [Stgo, Conce, Antof]
V = np.array([
    [1300, 900, 800],
    [2100, 1700, 1500],
    [1500, 1200, 900]
])

# P: [Precio_Hamb, Precio_Comp, Precio_Mat]
P = np.array([
    [4200, 1500, 3200]
])

# 2. Calcular I = P * V
# Orden P(1x3) * V(3x3) -> Resultado I(1x3)
I = np.dot(P, V)

print("--- 2. Matriz I (Ingresos por Sucursal) ---")
print(I)

# 3. Interpretación de elementos
v_32 = V[2, 1]  # Fila 3 (Mateadas), Col 2 (Concepción)
p_12 = P[0, 1]  # Fila 1, Col 2 (Precio Completos)
i_13 = I[0, 2]  # Fila 1, Col 3 (Ingreso Antofagasta)

print("\n--- 3. Interpretación de Elementos ---")
print(f"v_32 ({v_32}): Cantidad de Mateadas (producto 3) vendidas en Concepción (sucursal 2).")
print(f"p_12 ({p_12}): Precio de los Completos (producto 2), que es $1500.")
print(f"i_13 ({i_13}): Ingreso total (en pesos) del fin de semana en la sucursal de Antofagasta (sucursal 3).")

--- 2. Matriz I (Ingresos por Sucursal) ---
[[13410000 10170000  8490000]]

--- 3. Interpretación de Elementos ---
v_32 (1200): Cantidad de Mateadas (producto 3) vendidas en Concepción (sucursal 2).
p_12 (1500): Precio de los Completos (producto 2), que es $1500.
i_13 (8490000): Ingreso total (en pesos) del fin de semana en la sucursal de Antofagasta (sucursal 3).


# Problema 3

Una fábrica, para un mismo tipo de artículo eléctrico produce $2$ modelos, $A$ y $B$. Las filas de la matriz $M$, en el orden mencionado, nos muestran la cantidad de transistores y resistores que se requieren por cada artículo, según cada modelo. Por otra parte, las filas de la matriz $Q$ nos reportan las cantidades producidas de cada modelo para las tres primeras semanas del mes pasado.

<br>

\begin{split}
M = \begin{pmatrix}
 9 &  14 \\
 4 &  5  \\
\end{pmatrix} \ \ \ \ \ \ \ \ Q = \begin{pmatrix}
 200 &  240 & 220 \\
 175 &  210 & 215 \\
\end{pmatrix}
\end{split}

<br>

Además, considere las matrices $G = M \cdot Q$ y $H = Q \cdot M$.

1. Indique el orden de $M$ y $Q$.
2. ¿Es posible calcular las matrices $G$ y $H$? Justifique.
3. Determine utilizando *Python* la matriz $G$ e interprete los elementos $g_{23}$  y $g_{12}$.
4. ¿Cuántos resistores se utilizaron durante las tres semanas?

In [ ]:
import numpy as np

# M: Filas [Transistores, Resistores], Cols [A, B]
M = np.array([
    [9, 14],
    [4,  5]
])

# Q: Filas [A, B], Cols [Sem1, Sem2, Sem3]
Q = np.array([
    [200, 240, 220],
    [175, 210, 215]
])

# 3. Calcular G = M * Q
G = np.dot(M, Q)
print("--- 3. Matriz G (Componentes x Semana) ---")
print(G)

# Interpretación
g_23 = G[1, 2] # Fila 2 (Resistores), Col 3 (Semana 3)
g_12 = G[0, 1] # Fila 1 (Transistores), Col 2 (Semana 2)

print("\n--- Interpretación G ---")
print(f"g_23 ({g_23}): Es la cantidad total de Resistores (fila 2) utilizados en la Semana 3 (columna 3).")
print(f"g_12 ({g_12}): Es la cantidad total de Transistores (fila 1) utilizados en la Semana 2 (columna 2).")

# 4. Total de resistores
# Los resistores son la Fila 2 de la matriz G. Sumamos esa fila.
total_resistores = np.sum(G[1, :])
print(f"\n--- 4. Total de Resistores ---")
print(f"Se utilizaron {total_resistores} resistores en total (suma de la fila 2 de G).")

# Problema 4

Una empresa de telecomunicaciones necesita optimizar la distribución de su infraestructura de red en Iquique, Santiago y Concepción. Las columnas de la matriz $R$, en el orden mencionado, representan la cantidad de routers y switches que se deben instalar en cada ciudad. La matriz $C$ muestra el costo de instalación, en pesos, de cada router y switch.

<br>

\begin{split}
R = \begin{pmatrix}
 50 &  70 \\
 80 &  110  \\
 60 &  90  \\
\end{pmatrix} \ \ \ \ \ \ C = \begin{pmatrix}
 80000 \\
 45000 \\
\end{pmatrix}
\end{split}

<br>

1. Calcula utilizando *Python* el costo total de instalación para cada ciudad y almacénalo en la matriz $T$.
2. ¿Cuál es la ciudad que tiene mayor costo de instalación?
3. Si se aplica un descuento del $10\%$ en el costo de instalación de los switches, calcula el nuevo costo total de instalación para cada ciudad.

In [ ]:
import numpy as np

# R: Filas [Iqq, Stgo, Conce], Cols [Routers, Switches]
R = np.array([
    [50, 70],
    [80, 110],
    [60, 90]
])

# C: Filas [Costo_Router, Costo_Switch]
C = np.array([
    [80000],
    [45000]
])

# 1. Calcular T = R * C
# Orden R(3x2) * C(2x1) -> Resultado T(3x1)
T = np.dot(R, C)
print("--- 1. Matriz T (Costo Total por Ciudad) ---")
print(T)

# 2. Ciudad con mayor costo
costos = T.flatten() # Convertir la matriz columna a una lista simple
ciudades = ['Iquique', 'Santiago', 'Concepción']
indice_max = np.argmax(costos) # Encuentra la posición del valor más alto
print(f"\n--- 2. Ciudad con Mayor Costo ---")
print(f"La ciudad con mayor costo es {ciudades[indice_max]} con ${costos[indice_max]:,.0f}.")

# 3. Nuevo costo con descuento en switches
C_nuevo = np.array([
    [80000],
    [45000 * 0.90] # Costo Switch con 10% de descuento
])

T_nuevo = np.dot(R, C_nuevo)
print("\n--- 3. Nuevo Costo Total con Descuento ---")
print(T_nuevo.astype(int))

# Problema 5

Una empresa de servicios en la nube distribuye datos entre tres *Data Center*. La matriz $D$ muestra el volumen de datos (en terabytes) almacenados en cada *Data Center* durante los tres primeros meses del año. Mientras que la matriz $C$ muestra los costos (en dólares) de almacenamiento por terabyte en cada *Data Center*.

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
& \ \ \ \ \ \ \ DC_{1} &   DC_{2} & DC_{3}&
\end{matrix} & \\
&D = \begin{pmatrix}
100 & 150 & 200 \\
120 & 180 & 220 \\
140 & 210 & 250
\end{pmatrix} & \begin{matrix}
Ene\\
Feb\\
Mar
\end{matrix}
\end{matrix}
\ \ \ \ \ \ \ \ \ \ \ \ \ \
\begin{matrix}
& \begin{matrix}
\   
\end{matrix} & \\
&C = \begin{pmatrix}
50 \\
40 \\
30
\end{pmatrix}  \begin{matrix}
DC_{1}\\
DC_{2}\\
DC_{3}
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

1. Calcula utilizando *Python* la matriz $T = D \cdot C$.
2. Un trabajador indica que en febrero el costo por almacenamiento fue el más alto, ¿es cierta su afirmación?
3. Debido a la inflación, el costo de almacenamiento por terabyte aumenta en un $2,3\%$. Calcula el nuevo costo total de almacenamiento por mes e interprete cada uno de los elementos de la nueva matriz.

In [ ]:
import numpy as np

# D: Filas [Ene, Feb, Mar], Cols [DC1, DC2, DC3]
D = np.array([
    [100, 150, 200],
    [120, 180, 220],
    [140, 210, 250]
])

# C: Filas [Costo_DC1, Costo_DC2, Costo_DC3]
C = np.array([
    [50],
    [40],
    [30]
])

# 1. Calcular T = D * C
# Orden D(3x3) * C(3x1) -> Resultado T(3x1)
T = np.dot(D, C)
print("--- 1. Matriz T (Costo Total por Mes) ---")
print(T)

# 2. Afirmación del trabajador (Febrero = Fila 2, índice 1)
costos_mes = T.flatten()
costo_enero = costos_mes[0]
costo_febrero = costos_mes[1]
costo_marzo = costos_mes[2]

print("\n--- 2. Afirmación del Trabajador ---")
if costo_febrero > costo_enero and costo_febrero > costo_marzo:
    print(f"La afirmación es CIERTA. Febrero ({costo_febrero}) fue el más alto.")
else:
    print(f"La afirmación es FALSA. El mes más alto fue Marzo ({costo_marzo}).")

# 3. Nuevo costo (aumento 2.3%)
C_nuevo = C * 1.023
T_nuevo = np.dot(D, C_nuevo)

print("\n--- 3. Nuevo Costo Total (con aumento 2.3%) ---")
print(np.round(T_nuevo, 2))
print("\nInterpretación:")
print(f"El nuevo costo total en Enero (fila 1) será de ${T_nuevo[0,0]:,.2f}")
print(f"El nuevo costo total en Febrero (fila 2) será de ${T_nuevo[1,0]:,.2f}")
print(f"El nuevo costo total en Marzo (fila 3) será de ${T_nuevo[2,0]:,.2f}")

# Problema 6

Una compañía que fabrica un determinado producto, tiene $4$ plantas de producción y $5$ bodegas de almacenamiento. La matriz $T$ muestra las unidades de este producto que se generan mensualmente en la planta $i$ y que son transportadas a la bodega $j$, para quedar almacenadas allí durante el mes en que fueron producidas.

Además, la matriz $C$ detalla, para el primer semestre del presente año, el costo unitario (en dólares) de almacenamiento del producto durante el mes $j$ en la bodega $i$.

<br>

\begin{split}
T = \begin{pmatrix}
 500 &  400  &  300 & 200 & 100 \\
 600 &  500  &  400 & 300 & 200 \\
 700 &  600  &  500 & 400 & 300 \\
 800 &  700  &  600 & 500 & 400 \\
\end{pmatrix} \ \ \ \ \ \ C = \begin{pmatrix}
 5 &  6  &  7 &  8  &  9 & 6 \\
 4 &  5  &  6 &  7  &  8 & 7 \\
 3 &  4  &  5 &  6  &  7 & 9 \\
 2 &  3  &  4 &  5  &  6 & 6 \\
 8 &  5  &  6 &  3  &  7 & 5 \\
\end{pmatrix}
\end{split}

<br>

1. Determina la matriz $G = T \cdot C$.
2. Interpreta los elementos $t_{14}$, $c_{53}$ y $g_{35}$.
3. ¿Cuánto cuesta almacenar una unidad del producto en la bodega $4$ durante marzo de este año?
4. ¿Cuánto dinero gasta la empresa por almacenar la producción mensual de la planta $2$ durante el mes de abril?


In [ ]:
import numpy as np

# T: Filas [Planta 1-4], Cols [Bodega 1-5]
T = np.array([
    [500, 400, 300, 200, 100],
    [600, 500, 400, 300, 200],
    [700, 600, 500, 400, 300],
    [800, 700, 600, 500, 400]
])

# C: Filas [Bodega 1-5], Cols [Mes 1-6]
C = np.array([
    [5, 6, 7, 8, 9, 6],
    [4, 5, 6, 7, 8, 7],
    [3, 4, 5, 6, 7, 9],
    [2, 3, 4, 5, 6, 6],
    [8, 5, 6, 3, 7, 5]
])

# 1. Calcular G = T * C
# Orden T(4x5) * C(5x6) -> Resultado G(4x6)
G = np.dot(T, C)
print("--- 1. Matriz G (Costo total por Planta y Mes) ---")
print(G)

# 2. Interpretación
t_14 = T[0, 3] # Fila 1 (Planta 1), Col 4 (Bodega 4)
c_53 = C[4, 2] # Fila 5 (Bodega 5), Col 3 (Marzo)
g_35 = G[2, 4] # Fila 3 (Planta 3), Col 5 (Mayo)

print("\n--- 2. Interpretación de Elementos ---")
print(f"t_14 ({t_14}): Unidades producidas por la Planta 1 y transportadas a la Bodega 4.")
print(f"c_53 ({c_53}): Costo unitario ($5) de almacenamiento en la Bodega 5 durante el mes de Marzo (mes 3).")
print(f"g_35 ({g_35}): Costo total (en dólares) de almacenar la producción de la Planta 3 durante el mes de Mayo (mes 5).")

# 3. Costo bodega 4 durante marzo
# Fila 4 (Bodega 4), Col 3 (Marzo)
costo_b4_m3 = C[3, 2]
print(f"\n--- 3. Costo Específico ---")
print(f"El costo unitario en la Bodega 4 durante Marzo es de: ${costo_b4_m3}")

# 4. Gasto planta 2 durante abril
# Fila 2 (Planta 2), Col 4 (Abril)
gasto_p2_m4 = G[1, 3]
print("\n--- 4. Gasto Específico ---")
print(f"El gasto de la Planta 2 durante Abril es de: ${gasto_p2_m4}")

# Problema 7

Una empresa dedicada al desarrollo de software, que cuenta con tres sucuersales, necesita renovar los siguientes implementos para su personal: laptop de alto rendimiento, monitor externo de alta resolución, teclado mecánico, mouse ergonómico y disco duro de alta capacidad. Para esto, decide cotizar con tres proveedores y así encontrar el precio más conveniente para realizar la compra. La matriz $F$, en el orden mencionado, indica la cantidad de artículos que necesita comprar para cada sucursal. La matriz $G$ indica el precio unitario (en miles de pesos) de cada producto por proveedor.

<br>

\begin{split}
F = \begin{pmatrix}
 7 &  6  &  15 & 17 & 18 \\
 5 &  10  &  20 & 13 & 12 \\
 8 &  4  &  12 & 18 & 9 \\
\end{pmatrix} \ \ \ \ \ \ G = \begin{pmatrix}
 1700 &  1750 &  1800 \\
  868 &  803  &  840  \\
  165 &  160  &  150  \\
  70  &  73  &   65   \\
  110 &  124  &  115  \\
\end{pmatrix}
\end{split}

<br>

1. Calcula utilizando *Python* la matriz $D = F \cdot G$.
2. Interpreta los elementos $d_{33}$ y $d_{21}$.
3. ¿Cuál es el proveedor más conveniente para realizar todas las compras?
4. Si escoge el proveedor más conveniente, ¿en qué sucursal deberá invertir más dinero por la renovación de los implementos?

In [2]:
import numpy as np

# F: Filas [Suc 1-3], Cols [Laptop, Monitor, Teclado, Mouse, Disco]
F = np.array([
    [ 7,  6, 15, 17, 18],
    [ 5, 10, 20, 13, 12],
    [ 8,  4, 12, 18,  9]
])

# G: Filas [Artículos], Cols [Prov 1, Prov 2, Prov 3]
G = np.array([
    [1700, 1750, 1800],
    [ 868,  803,  840],
    [ 165,  160,  150],
    [  70,   73,   65],
    [ 110,  124,  115]
])

# 1. Calcular D = F * G
# Orden F(3x5) * G(5x3) -> Resultado D(3x3)
D = np.dot(F, G)
print("--- 1. Matriz D (Costo Sucursal x Proveedor) ---")
print(D)

# 2. Interpretación
d_33 = D[2, 2] # Fila 3 (Suc 3), Col 3 (Prov 3)
d_21 = D[1, 0] # Fila 2 (Suc 2), Col 1 (Prov 1)

print("\n--- 2. Interpretación de Elementos ---")
print(f"d_33 ({d_33}): Costo total (en miles de pesos) para la Sucursal 3 si compra todo al Proveedor 3.")
print(f"d_21 ({d_21}): Costo total (en miles de pesos) para la Sucursal 2 si compra todo al Proveedor 1.")

# 3. Proveedor más conveniente (Sumar columnas de D)
costo_por_proveedor = np.sum(D, axis=0) # axis=0 suma verticalmente (columnas)
proveedores = ['Proveedor 1', 'Proveedor 2', 'Proveedor 3']
indice_min = np.argmin(costo_por_proveedor)

print("\n--- 3. Proveedor más Conveniente ---")
print(f"Costo Prov 1: {costo_por_proveedor[0]:,.0f} mil pesos")
print(f"Costo Prov 2: {costo_por_proveedor[1]:,.0f} mil pesos")
print(f"Costo Prov 3: {costo_por_proveedor[2]:,.0f} mil pesos")
print(f"El proveedor más conveniente es el {proveedores[indice_min]} (índice {indice_min}).")

# 4. Sucursal que invertirá más (con el proveedor más conveniente)
# Extraemos la columna del proveedor más conveniente (índice 2, Prov 3)
costos_sucursales_prov3 = D[:, 2]
sucursales = ['Sucursal 1', 'Sucursal 2', 'Sucursal 3']
indice_max_suc = np.argmax(costos_sucursales_prov3)

print("\n--- 4. Sucursal con Mayor Inversión (con Prov. 3) ---")
print(f"La sucursal que invertirá más dinero es la {sucursales[indice_max_suc]} (índice {indice_max_suc}) con {costos_sucursales_prov3[indice_max_suc]:,.0f} mil pesos.")

--- 1. Matriz D (Costo Sucursal x Proveedor) ---
[[22753 22941 23065]
 [22710 22417 22625]
 [21302 21562 21765]]

--- 2. Interpretación de Elementos ---
d_33 (21765): Costo total (en miles de pesos) para la Sucursal 3 si compra todo al Proveedor 3.
d_21 (22710): Costo total (en miles de pesos) para la Sucursal 2 si compra todo al Proveedor 1.

--- 3. Proveedor más Conveniente ---
Costo Prov 1: 66,765 mil pesos
Costo Prov 2: 66,920 mil pesos
Costo Prov 3: 67,455 mil pesos
El proveedor más conveniente es el Proveedor 1 (índice 0).

--- 4. Sucursal con Mayor Inversión (con Prov. 3) ---
La sucursal que invertirá más dinero es la Sucursal 1 (índice 0) con 23,065 mil pesos.


# Problema 8

Sea la matriz $A$:

<br>

\begin{split}
A = \begin{pmatrix}
 3 &  1  &  2 \\
 1 &  2  &  1 \\
 4 &  1  &  3 \\
\end{pmatrix}
\end{split}

<br>

1. Calcula, utilizando *Python*, la matriz $A^{-1}$.
2. Calcula la matriz $I = A \cdot A^{-1}$.
3. Calcula la matriz $I^{-1}$. Analiza este resultado, comparando con los resultados obtenidos en los ítems anteriores. ¿Puedes encontrar alguna relación para estas matrices?

In [4]:
import numpy as np

A=np.array([[3,1,2],[1,2,1],[4,1,3]])

A_inv=np.linalg.inv(A)
print(f'1)la matriz inversa de A es:\n\n{A_inv}')

I=np.round(np.dot(A,A_inv))
print(f'2)la matriz I es:\n\n{I}')

I_inv=np.linalg.inv(I)
print(f'3)la matriz inversa de I es: \n\n{I_inv}')

1)la matriz inversa de A es:

[[ 2.5 -0.5 -1.5]
 [ 0.5  0.5 -0.5]
 [-3.5  0.5  2.5]]
2)la matriz I es:

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3)la matriz inversa de I es: 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3) la matriz I y su inversa son iguales ya que esta matriz identidad actua como el 1 en la multiplicacion de numeros y por ende el inverso de esta matriz neutra es la misma matriz

# Problema 9

1. Considera que el siguiente sistema de ecuaciones:

<br>

\begin{split}
2x + y & = 7 \\
3x - 2y & = 21
\end{split}

<br>

$\hspace{1cm}$ Se puede escribir matricialmente como:

<br>

\begin{split}
\begin{pmatrix}
 2  &  1 \\
 3 & -2 \\
\end{pmatrix} \cdot \begin{pmatrix}
 x \\
 y \\
\end{pmatrix} = \begin{pmatrix}
 7 \\
 21 \\
\end{pmatrix}
\end{split}

<br>

* Utiliza la matriz inversa para encontrar los valores de $x$ e $y$ que permiten satisfacer ambas ecuaciones simultáneamente.

<br>

2. Considera que el siguiente sistema de ecuaciones:

<br>

\begin{split}
h + m & = 60 \\
0,16h + 0,2m & = 11
\end{split}

<br>

$\hspace{1cm}$ Se puede escribir matricialmente como:

<br>

\begin{split}
\begin{pmatrix}
 1  &  1 \\
 0,16 & 0,2 \\
\end{pmatrix} \cdot \begin{pmatrix}
 h \\
 m \\
\end{pmatrix} = \begin{pmatrix}
 60 \\
 11 \\
\end{pmatrix}
\end{split}

<br>

* Utiliza la matriz inversa para encontrar los valores de $h$ y $m$ que permiten satisfacer el sistema de ecuaciones.

In [8]:
import numpy as np
# Definimos las matrices A (Materiales x Modelo) y B (Modelo x Mes)
A = np.array([[2,1],[3,-2]])

B = np.array([[7], [21]])

A_inv = np.linalg.inv(A)

C = np.dot(A_inv, B)
print(f'1)la matriz de las incognitas es:\n\n{C}')

D = np.array([[1, 1],[0.16, 0.2]])

E = np.array([[60], [11]])

D_inv = np.linalg.inv(D)

F = np.dot(D_inv, E)
print(f'2)la matriz de las incognitas es:\n\n{F}')


1)la matriz de las incognitas es:

[[ 5.]
 [-3.]]
2)la matriz de las incognitas es:

[[25.]
 [35.]]


los valores de X e Y que dan solucion al sistema de ecuacion 1 son $x=5$ e Y = -3

# Problema 10

Considera los siguientes sistemas de ecuaciones:

<br>

**a)**
\begin{split}
2m + 4p & = 2900 \\
3m + 3p & = 3150
\end{split}
<br>
<br>
**b)**
\begin{split}
n + v & = 160 \\
50n + 300v & = 23000
\end{split}

<br>

1. Escribe ambos sistemas de ecuaciones de forma matricial.
1. Utiliza la matriz inversa para calcular las soluciones de ambos sistemas de ecuaciones.




# Problema 11

Una persona tiene $\$8000$ en monedas de $\$10$ y de $50$. El sistema de ecuaciones que representa la situación es el siguiente:

<br>

\begin{split}
x + y & = 200 \\
10x + 50y & = 8000
\end{split}

<br>

1. ¿Qué representa cada variable?
2. Explica qué representa cada una de las ecuaciones del sistema.
3. ¿Cuántas monedas de $\$10$ y de $\$50$ tiene?

# Problema 12

En una granja hay $132$ animales entre patos y vacas. En total hay $402$ patas. El sistema que modela la situación planteada es:

<br>

\begin{split}
p + v & = 132 \\
2p + 4v & = 402
\end{split}

<br>

1. ¿Qué representan las incógnitas del sistema?
2. ¿Cuántos patos hay?

# Problema 13

Luis compró $5$ cables USB y $6$ pendrives, en total canceló $\$82.890$. Pablo compró a los mismos precios $3$ cables USB y $7$ pendrives, y canceló $\$59.900$.

El sistema que modela el problema es:

<br>

\begin{split}
5x + 6y &= 82890 \\
3x +  7y &= 59900
\end{split}

<br>


1. ¿Qué representa cada incógnita en el contexto del problema?
2. Determina cuánto pagaron por cada cable USB.