In [ ]:
#¿Cuántos milisegundos tarda el algoritmo en ejecutar una lista de 101 elementos?
def T(n):
    return 3*n+5
print(f'{T(101)}')

308


In [ ]:
#La forma algebraica de la función que relaciona ambas variables es:
import numpy as np
x = np.array([5,10,15,20])
y = np.array([200,300,400,500])

pendiente, intercepto = np.polyfit(x, y, 1)

print(f'la pendiente es: {pendiente} y el coeficiente de posicion es: {intercepto}')

la pendiente es: 20.0 y el coeficiente de posicion es: 100.00000000000004


In [ ]:
#¿Cuántos usuarios, aproximadamente tendrá la aplicación luego de transcurrir 1 año? Aproxime su resultado al entero.
def U(t):
    return 1000*np.exp(0.1*t)
print(f'{U(12)}')

3320.116922736548


In [42]:
#¿Cuántos años deben pasar que la base de datos tenga un tamaño de 20 TB?
from scipy.optimize import fsolve

def D(t):
    return 2*1.2**t-20
xo = np.linspace(0, 20, 1)
solucion = fsolve(D,xo)
print(f'{solucion}')


[12.62925314]


In [ ]:
#Se tiene un sistema para generar números de serie para un determinado producto. El primer número de serie es 1.000 y cada número de serie se incrementará en 5 respecto al número de serie anterior. ¿Cuál será el número de serie del producto asociado a la posición 25?
a_1=1000
d=5
n=25
a_25=a_1+(n-1)*d

print(f'{a_25}')

1120


In [ ]:
#Sea la sucesión a_n= 5n**3-2n. ¿Cuál es el término de la décima quinta posición?
def a(n):
    return 5*n**3-2*n

print(f'{a(15)}')

16845


In [ ]:
#Un algoritmo demora en procesar un solo registro en 2,1 minutos; dos registros en 2,2 y tres registros en 2,3 minutos. Si se sigue el mismo patrón de crecimiento, ¿cuántos registros procesa el algoritmo en 5,6 minutos?
#opcion 1
final = 5.6
termino = 0
dif = final - termino
n = 0
a_1 =2.1
d=0.1
while dif > 0:
  n += 1
  termino = a_1+(n-1)*d
  dif = final - termino
print(f'El término 5.6 se ubica en la posición {n} de la sucesión.')

El término 5.6 se ubica en la posición 36 de la sucesión.


#opcion 2
$$5,6 = 2,1+(n-1)*0,1$$

$$5,6-2,1=(n-1)*0.1$$

$$3,5/0.1=n-1$$

$$35+1=n$$

$$36=n$$


In [ ]:
#En una tienda recién inaugurada, la primera semana ha vendido 300 unidades de un producto determinado y se espera que las ventas aumenten en 40 unidades cada semana. ¿Cuántas unidades del producto se proyecta vender en total al cabo de 2 meses? Considere que 1 mes equivale a 4 semanas.

a_1=300
d=40
sucesion = []
for i in range(8):
    n = i + 1
    sucesion.append(a_1+(n-1)*d)
suma = sum(sucesion)
print(f'{suma}')

3520


In [ ]:
#En una sucesión geométrica, el cuarto término es 24 y el sexto término es 96. Determine el valor del noveno término.
# El noveno término es 
a_4=24
a_6=96

r=(a_6/a_4)**(1/2)
print(f'r={r}')
a_1=a_4/r**3
print(f'a_1={a_1}')
n=9
a_9=a_1*r**(n-1)
print(f'a_9={a_9}')

r=2.0
a_1=3.0
a_9=768.0


In [ ]:
#Si un día, el servidor B aumenta su consumo en un 20%, ¿cuántos gigabytes consumiría en dicho día por concepto de almacenamiento en la aplicación 3?

import numpy as np

B=np.array([[1,7],
            [4,6],
            [6,5]])
A=np.array([[4,6],
            [8,5],
            [2,7]])

B_1=1.2*B
print(f'{B_1}')


[[1.2 8.4]
 [4.8 7.2]
 [7.2 6. ]]


In [ ]:
#¿En cuánto está evaluado, para el miércoles de la semana pasada, el total de acciones que posee en esta empresa el inversionista 8?

A = np.fromfunction(lambda i, j: 20*(i+1)*(j+1), (15,10))
E = np.fromfunction(lambda i, j: 4*(i+1)+(j+1), (10,5))

C=np.dot(A,E)
print(f'{C}')

[[ 31900.  33000.  34100.  35200.  36300.]
 [ 63800.  66000.  68200.  70400.  72600.]
 [ 95700.  99000. 102300. 105600. 108900.]
 [127600. 132000. 136400. 140800. 145200.]
 [159500. 165000. 170500. 176000. 181500.]
 [191400. 198000. 204600. 211200. 217800.]
 [223300. 231000. 238700. 246400. 254100.]
 [255200. 264000. 272800. 281600. 290400.]
 [287100. 297000. 306900. 316800. 326700.]
 [319000. 330000. 341000. 352000. 363000.]
 [350900. 363000. 375100. 387200. 399300.]
 [382800. 396000. 409200. 422400. 435600.]
 [414700. 429000. 443300. 457600. 471900.]
 [446600. 462000. 477400. 492800. 508200.]
 [478500. 495000. 511500. 528000. 544500.]]


In [ ]:
#¿Cuántas estaciones de trabajo y servidores se han comprado?
A=np.array([[4,8],
            [2,6]])

B=np.array([[72],
            [40]])
A_inv=np.linalg.inv(A)

C=np.dot(A_inv,B)
print(f'{C}')

[[14.]
 [ 2.]]
